// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTY-fGQ7T6var5H73Iu3v037DaFCdFkLU',
    appId: '1:1011238401507:web:e41b27eeb2d925a745dcd6',
    messagingSenderId: '1011238401507',
    projectId: 'app-gki-dnt',
    authDomain: 'app-gki-dnt.firebaseapp.com',
    storageBucket: 'app-gki-dnt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvR9MbixRDD8b7d5XhJu5mmvsLEFaqZtA',
    appId: '1:1011238401507:android:fc76fdd51b98b1a945dcd6',
    messagingSenderId: '1011238401507',
    projectId: 'app-gki-dnt',
    storageBucket: 'app-gki-dnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRxvI_wKVbg8L-F6MxXM0bCr9lc4ynS4',
    appId: '1:1011238401507:ios:6f8030f264b6fa5b45dcd6',
    messagingSenderId: '1011238401507',
    projectId: 'app-gki-dnt',
    storageBucket: 'app-gki-dnt.firebasestorage.app',
    iosBundleId: 'com.example.appGkiDnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiRxvI_wKVbg8L-F6MxXM0bCr9lc4ynS4',
    appId: '1:1011238401507:ios:6f8030f264b6fa5b45dcd6',
    messagingSenderId: '1011238401507',
    projectId: 'app-gki-dnt',
    storageBucket: 'app-gki-dnt.firebasestorage.app',
    iosBundleId: 'com.example.appGkiDnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTY-fGQ7T6var5H73Iu3v037DaFCdFkLU',
    appId: '1:1011238401507:web:5fafc3f612a740c145dcd6',
    messagingSenderId: '1011238401507',
    projectId: 'app-gki-dnt',
    authDomain: 'app-gki-dnt.firebaseapp.com',
    storageBucket: 'app-gki-dnt.firebasestorage.app',
  );

}